[package]
name = "socket-programming"
version = "0.1.0"
authors = ["akthrms <akt.hrms@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.8.2"
anyhow = "1.0"
